#!/bin/sh

case `uname -m`.`uname -s` in
     x86_64.Darwin)
        cfg="x86_64.darwin"
        ;;
     x86_64.Linux)
        cfg="x86_64.linux"
        ;;
     armv7l.Linux)
        cfg="armv7l.linux"
        ;;
     i686.CYGWIN*)
         cfg="x86.windows"
         ;;
     x86_64.CYGWIN*)
         cfg="x86_64.windows"
         ;;
     *)
         echo "$0: unknown configuration"
         exit 1
         ;;
esac

echo $cfg
