#!/bin/bash

for n in 1 2 3 4 5 6 7 8 9 10 ; do
    echo "************** $n ***************"
    k=0
    pids=""
    sleep 1
    while [ $k -lt $n ] ; do
        k=`expr $k + 1`
        gen/subscriber & pids="$pids $!"
    done
    sleep 2
    gen/publisher 1 & pids="$pids $!"
    sleep 10
    kill -INT $pids
    sleep 2
    kill -9 $pids
done
