/****************************************************************

  Generated by Vortex Lite IDL to C Translator
  File name: RoundTrip.h
  Source: RoundTrip.idl
  Generated: Mon Dec 05 11:50:37 CET 2016
  Vortex Lite: V2.1.0

*****************************************************************/

#include "dds.h"

#ifndef _DDSL_ROUNDTRIP_H_
#define _DDSL_ROUNDTRIP_H_


#ifdef __cplusplus
extern "C" {
#endif


typedef struct RoundTripModule_DataType
{
  dds_sequence_t payload;
} RoundTripModule_DataType;

extern const dds_topic_descriptor_t RoundTripModule_DataType_desc;

#define RoundTripModule_DataType__alloc() \
((RoundTripModule_DataType*) dds_alloc (sizeof (RoundTripModule_DataType)));

#define RoundTripModule_DataType_free(d,o) \
dds_sample_free ((d), &RoundTripModule_DataType_desc, (o))


typedef struct RoundTripModule_Address
{
  char * ip;
  int32_t port;
} RoundTripModule_Address;

extern const dds_topic_descriptor_t RoundTripModule_Address_desc;

#define RoundTripModule_Address__alloc() \
((RoundTripModule_Address*) dds_alloc (sizeof (RoundTripModule_Address)));

#define RoundTripModule_Address_free(d,o) \
dds_sample_free ((d), &RoundTripModule_Address_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_ROUNDTRIP_H_ */
