module TypesArrayKey {
    typedef enum enumkey {
        ENUMKEY_1,
        ENUMKEY_2
    } enum_enumkey;

    struct enum_enumkey_arraytypekey {
        enum_enumkey key[20]; //@Key
    };
    #pragma keylist enum_enumkey_arraytypekey key

    struct long_arraytypekey {
        long key[20]; //@Key
    };
#pragma keylist long_arraytypekey key

    typedef long long longlong;
    struct longlong_arraytypekey {
        longlong key[20]; //@Key
    };
#pragma keylist longlong_arraytypekey key

    typedef unsigned short unsignedshort;
    struct unsignedshort_arraytypekey {
        unsignedshort key[20]; //@Key
    };
#pragma keylist unsignedshort_arraytypekey key

    typedef unsigned long unsignedlong;
    struct unsignedlong_arraytypekey {
        unsignedlong key[20]; //@Key
    };
#pragma keylist unsignedlong_arraytypekey key

    typedef unsigned long long unsignedlonglong;
    struct unsignedlonglong_arraytypekey {
        unsignedlonglong key[20]; //@Key
    };
#pragma keylist unsignedlonglong_arraytypekey key

    struct float_arraytypekey {
        float key[20]; //@Key
    };
#pragma keylist float_arraytypekey key

    struct double_arraytypekey {
        double key[20]; //@Key
    };
#pragma keylist double_arraytypekey key

    struct char_arraytypekey {
        char key[128]; //@Key
    };
#pragma keylist char_arraytypekey key

    struct boolean_arraytypekey {
        boolean key[128]; //@Key
    };
#pragma keylist boolean_arraytypekey key

    struct octet_arraytypekey {
        octet key[128]; //@Key
    };
#pragma keylist octet_arraytypekey key

    struct alltypeskey {
        long                l; //@Key
        long long           ll; //@Key
        unsigned short      us; //@Key
        unsigned long       ul; //@Key
        unsigned long long  ull; //@Key
        float               f; //@Key
        double              d; //@Key
        char                c; //@Key
        boolean             b; //@Key
        octet               o; //@Key
        string              s; //@Key
    };
#pragma keylist alltypeskey l ll us ul ull f d c b o s

    struct stringkey {
        string payload;
        string key; //@Key
        sequence<string> seq_payload; // Swapping field key and seq_payload trigger an assert.
    };
#pragma keylist stringkey key
};
